version: '3.8'

services:
  apigateway:
    image: devopsexmaproject.apigateway:dev
    build:
      context: .
      dockerfile: DevOpsExmaProject.ApiGateway/Dockerfile
    ports:
      - "7275:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  identotyapi:
    image: devopsexmaproject.identity:dev
    build:
      context: .
      dockerfile: DevOpsExmaProject.Identity/Dockerfile
    ports:
      - "7203:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  mp3api:
    image: devopsexmaproject.mp3api:dev
    build:
      context: .
      dockerfile: DevOpsExmaProject.Mp3Api/Dockerfile
    ports:
      - "7273:8080"
    volumes:
      - image_volume:/images
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  reactui:
    image: devopsexmaproject.ui:latest 
    build:
      context: ./DevOpsExmaProject.Ui  
      dockerfile: Dockerfile 
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

volumes:
  image_volume:
    driver: local
