
services:
  # redis
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - backend
  
  # rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - backend
  
  # db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mp3db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrongPassword2025!
    ports:
      - "1433:1433"
    volumes:
      - mp3db_data:/var/opt/mssql
    networks:
      - backend

  # apigateway
  apigateway:
    image: devopsexmaproject.apigateway:dev
    build:
      context: .
      dockerfile: DevOpsExmaProject.ApiGateway/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    networks:
      - backend

  # identityapi
  identityapi:
    image: devopsexmaproject.identity:dev
    build:
      context: .
      dockerfile: DevOpsExmaProject.Identity/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=mp3db;Initial Catalog=Mp3Db;User ID=sa;Password=MyStrongPassword2025!;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False
    depends_on:
      - db
    volumes:
      - dataprotection:/root/.aspnet/DataProtection-Keys
    networks:
      - backend

  # mp3api
  mp3api:
    image: devopsexmaproject.mp3webapi:dev
    build:
      context: .
      dockerfile: DevOpsExmaProject.Mp3WebApi/Dockerfile
    ports:
      - "5003:8080"
    volumes:
      - image_volume:/images
      - dataprotection:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=mp3db;Initial Catalog=Mp3Db;User ID=sa;Password=MyStrongPassword2025!;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False
    depends_on:
      - db
    networks:
      - backend

  # reactui
  # reactui:
  #   image: devopsexmaproject.ui:latest
  #   build:
  #       context: .
  #       dockerfile: devopsexmaproject.ui/Dockerfile
  #   ports:
  #   - "5173:5173"
  #   volumes:
  #     - ./devopsexmaproject.ui:/app
  #     - /app/node_modules 
  #   environment:
  #     - NODE_ENV=development
  #     - CHOKIDAR_USEPOLLING=true
  #   stdin_open: true
  #   tty: true
  #   networks:
  #   - backend


# volumes
volumes:
  image_volume:
    driver: local
  mp3db_data:
    driver: local
  dataprotection:
    driver: local

# networks
networks:
  backend:
    driver: bridge
